services:
  database:
    image: postgres:latest
    container_name: stats-db
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: ${STATS_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${STATS_DATABASE_PASSWORD}
      POSTGRES_DB: ${STATS_DATABASE_NAME}
    volumes:
      - ./.db-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]

  stats-service: 
    build:
      context: .
    container_name: stats-service
    environment:
      - STATS_DATABASE_HOST=${STATS_DATABASE_HOST}
      - STATS_DATABASE_PORT=${STATS_DATABASE_PORT}
      - STATS_DATABASE_NAME=${STATS_DATABASE_NAME}
      - STATS_DATABASE_SCHEMA=${STATS_DATABASE_SCHEMA}
      - STATS_DATABASE_USERNAME=${STATS_DATABASE_USERNAME}
      - STATS_DATABASE_PASSWORD=${STATS_DATABASE_PASSWORD}
      - STATS_ENVIRONMENT=${STATS_ENVIRONMENT}
    ports:
      - "3000:3000"
    depends_on:
      - database
    command: ["npm", "start", "dev"]

